/*
 * This file is generated by jOOQ.
*/
package cabanas.garcia.ismael.storeroom.module.storeroom.infrastructure.repository.jooq.autogen;


import cabanas.garcia.ismael.storeroom.module.storeroom.infrastructure.repository.jooq.autogen.tables.Products;
import cabanas.garcia.ismael.storeroom.module.storeroom.infrastructure.repository.jooq.autogen.tables.StoreroomProducts;
import cabanas.garcia.ismael.storeroom.module.storeroom.infrastructure.repository.jooq.autogen.tables.Storerooms;
import cabanas.garcia.ismael.storeroom.module.storeroom.infrastructure.repository.jooq.autogen.tables.records.ProductsRecord;
import cabanas.garcia.ismael.storeroom.module.storeroom.infrastructure.repository.jooq.autogen.tables.records.StoreroomProductsRecord;
import cabanas.garcia.ismael.storeroom.module.storeroom.infrastructure.repository.jooq.autogen.tables.records.StoreroomsRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>storeroom</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3",
        "schema version:storeroom_2018.11.19.0"
    },
    date = "2018-12-10T05:57:40.531Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ProductsRecord> PK_PRODUCTS = UniqueKeys0.PK_PRODUCTS;
    public static final UniqueKey<ProductsRecord> UQ_PRODUCTS_NAME = UniqueKeys0.UQ_PRODUCTS_NAME;
    public static final UniqueKey<StoreroomProductsRecord> PK_STOREROOM_PRODUCTS = UniqueKeys0.PK_STOREROOM_PRODUCTS;
    public static final UniqueKey<StoreroomProductsRecord> UQ_STOREROOM_PRODUCTS_NAME = UniqueKeys0.UQ_STOREROOM_PRODUCTS_NAME;
    public static final UniqueKey<StoreroomsRecord> PK_STOREROOMS = UniqueKeys0.PK_STOREROOMS;
    public static final UniqueKey<StoreroomsRecord> UQ_STOREROOMS_NAME = UniqueKeys0.UQ_STOREROOMS_NAME;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<StoreroomProductsRecord, StoreroomsRecord> STOREROOM_PRODUCTS__FK_STOREROOM_PRODUCTS_STOREROOM_ID = ForeignKeys0.STOREROOM_PRODUCTS__FK_STOREROOM_PRODUCTS_STOREROOM_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ProductsRecord> PK_PRODUCTS = createUniqueKey(Products.PRODUCTS, "pk_products", Products.PRODUCTS.P_ID);
        public static final UniqueKey<ProductsRecord> UQ_PRODUCTS_NAME = createUniqueKey(Products.PRODUCTS, "uq_products_name", Products.PRODUCTS.P_NAME);
        public static final UniqueKey<StoreroomProductsRecord> PK_STOREROOM_PRODUCTS = createUniqueKey(StoreroomProducts.STOREROOM_PRODUCTS, "pk_storeroom_products", StoreroomProducts.STOREROOM_PRODUCTS.SP_ID);
        public static final UniqueKey<StoreroomProductsRecord> UQ_STOREROOM_PRODUCTS_NAME = createUniqueKey(StoreroomProducts.STOREROOM_PRODUCTS, "uq_storeroom_products_name", StoreroomProducts.STOREROOM_PRODUCTS.SP_NAME);
        public static final UniqueKey<StoreroomsRecord> PK_STOREROOMS = createUniqueKey(Storerooms.STOREROOMS, "pk_storerooms", Storerooms.STOREROOMS.S_ID);
        public static final UniqueKey<StoreroomsRecord> UQ_STOREROOMS_NAME = createUniqueKey(Storerooms.STOREROOMS, "uq_storerooms_name", Storerooms.STOREROOMS.S_NAME);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<StoreroomProductsRecord, StoreroomsRecord> STOREROOM_PRODUCTS__FK_STOREROOM_PRODUCTS_STOREROOM_ID = createForeignKey(cabanas.garcia.ismael.storeroom.module.storeroom.infrastructure.repository.jooq.autogen.Keys.PK_STOREROOMS, StoreroomProducts.STOREROOM_PRODUCTS, "storeroom_products__fk_storeroom_products_storeroom_id", StoreroomProducts.STOREROOM_PRODUCTS.SP_STOREROOM_ID);
    }
}
