/*
 * This file is generated by jOOQ.
*/
package cabanas.garcia.ismael.storeroom.module.storeroom.infrastructure.framework.repository.jooq.autogen;


import cabanas.garcia.ismael.storeroom.module.storeroom.infrastructure.framework.repository.jooq.autogen.tables.Products;
import cabanas.garcia.ismael.storeroom.module.storeroom.infrastructure.framework.repository.jooq.autogen.tables.StoreroomProducts;
import cabanas.garcia.ismael.storeroom.module.storeroom.infrastructure.framework.repository.jooq.autogen.tables.Storerooms;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in storeroom
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3",
        "schema version:storeroom_2018.11.19.0"
    },
    date = "2018-12-10T05:57:40.531Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Storeroom products
     */
    public static final Products PRODUCTS = cabanas.garcia.ismael.storeroom.module.storeroom.infrastructure.framework.repository.jooq.autogen.tables.Products.PRODUCTS;

    /**
     * Storeroom products
     */
    public static final StoreroomProducts STOREROOM_PRODUCTS = cabanas.garcia.ismael.storeroom.module.storeroom.infrastructure.framework.repository.jooq.autogen.tables.StoreroomProducts.STOREROOM_PRODUCTS;

    /**
     * Storeroom
     */
    public static final Storerooms STOREROOMS = cabanas.garcia.ismael.storeroom.module.storeroom.infrastructure.framework.repository.jooq.autogen.tables.Storerooms.STOREROOMS;
}
