sudo: required

services:
  - docker

language: java

jdk:
  - oraclejdk8

env:
  global:
    - secure: "TFvIILR9nO5xgRUhiXab9nt6YE9XN/57ZWHYZMGNyuAgbxFoMG1HT9P1OGkL27jIYHz7wHS6UFBsZFx26yukB9znXeAZPGTKR2VVLVII7tDT+Ss2dvFulaFzv6Tm1xlPQC6R4YLHjMGIHPodDkQsr/WQpR1/u34D5HQxfMKQywnjC2V54t4u5Y3fY6UNb2D4IyjuUr5zPIeNt4F8DXbLIfF8215wWgvF41vA7q9ZRF9BF5X54HfnQXkrqHEDoLExptuPyoPyREWKyUVxCxVLA6z/HG9EFMxFT6Tts/Eq1OuEOzdYgnkf6BGtn/MiaTHOQtBCIhwfizQYfyn44ojwdquAKsNVVmP+Rtvxl5uMdaHwcG27RrFk5Sw1IzGAgX/APyGtrIMqCFrohATnmwIGvVleryCgWxSc8vJi7WryBjkhLQymyjsyTssXt5lC4NoLsp8wP3oLb2qmq4LaOhH7H8HEh9l50Pjp4pKWQ3XMlZl+x4HTGVkBMVK/5xJf3Bti9/aLd3xYpsidOz6DZ/63gpy0GmWJwBSUOx7iEHqIFQTHAXrbpFTxLD//m9c5chMUxMnYjd6zgv3a4Zu0c/LdtSYdvk9xBroJ/YTMaVGyPyFDnGdZp6lbz4Ye+vGgZgPs6A1Cw4S0k/KEjRfWO5vaaEtA25mG9BArVojZzxThCzM=" #DOCKER_USER
    - secure: "qv4W2QBXi6HPbSb6ZTvzsWAY78z/2KvBIB551ijeUgxiG+qvTTBaQ4pfRM9wq3QrzaynXZdsqRDRKc+gHOGpZFoa80cB2zjMsDql1tXs3+Qcsg8QG++EpH71aZK8sTN01ubvXCdOc/T5mpnlrwJPl1mJF7sPUddWd3XdAjG6RkhKF81wKNGIpK4FY7gYv4sQHNR5dNZUXeVPWzXsRncexl9ccnGWQDpc0aEgJ8SO6m7NIOtHk9sK23qxKtYVE1W5Z/QUFZxAMa3QE3kn8cOJ2j1Z0QXyADzb1eTHUK68R+fPZ4g01BIPyP5qcfnSDnALDFx6/AC/ZI+ZEtICxChzYJsx66ee07I0AvSAqJVB3irCskvBCrzYy625l1F8PPnZ3xH7rO+R4z+0aJJgeFKY5T8hgKwgF39R8dF4q5fEA16zTyPez4HAE2vH5OgG+LgMb2BrC90X56Ha73DP7D2cF20lQ/veZMACWeKH4sQsLoXFwDuG9weZvv6Fj6teVA8hQnQm6quXTnQpQ7L5i32CO19N9KRTVX/jh5m2I6KVz6oAdY6CZ/03bfHfb9XV2ngUdokEHQCnxJ2e/Qh7tiKmGRU5bEzs2EJbzeiCkhapRzL1UDkz0KwkTtOyPSOV7YUfeTyLbDVYC4hXfat1gNuuwvbwwqKyX6WWi7gcaOalE5c=" #DOCKER_PASS
    - secure: "NNXzL/nMhHSHyMeet17Fc+HJJKbNN/OnMhkPDoVhYGPabJSdbaomz/yT0v54+dpdoywv7VEIg2PULUGcRSq6PP0y25fun9QnSPlMiK1qfgFlTa+elXgOWYWu1OP3rWpuQuFycj+Oiq7/V9A5juqTQU2G4q8satCIwCVfM6Lq+clRtoO2GVkvPS2g28uzptB+uUoE7YZtMT8ujbK3/RT/tieRnL3+MYZfJuqBmHTN9PsfdpUciQ5hQyPkfmjDj0DflZfBrA/OdEarmEjH/BWaE7bi59Ym9Qa6ndWiAa9qtk2oHsMfxYX83qNzHeEkKS368aiJVzfcDhrPlhltvAeVzCV8VGopXK1mRHH2SO9oDar/qjVLQiTvm/RIguV+r/IkbZ4l5riHem2iHVdsdaCZccRo8C8jnFZ82x0VQu+azsg5OsLcS69Jo86w2dZIGGcV1aAnd4mDhNWtZQnc865yOact6DSYxy7xUm5KUngD6rGAsZfe9idAivPFLNMu67Z/U6cL0TSUYgNM4+YzIhXlnk2g7qmyPyC5qZJhdzMACFMzZqYTRqzeApDQcY/jVw4Denuo8s08kFf4O6Fi3Y7zx+mQp9V0RIfGFyA87cYO7845m05KyTDUG/BOA/RMjVujH386oNdwIncpzTYyzSreXesnv3ZMLZMJU51KoJYE6Bg=" #SONAR_TOKEN
    - DOCKER_IMAGE_NAME=ismaelcabanas14/storeroom-rest-api

script:
  - ./gradlew check test integrationTest jacocoTestCoverageVerification jacocoTestReport
  - sonar-scanner -X
  - docker build -t $DOCKER_IMAGE_NAME .
  - docker run -it -p 8000:8000 -d $DOCKER_IMAGE_NAME
  - ./gradlew acceptanceTest

addons:
  sonarcloud:
    organization: ismaelcabanas-github
    token:
      secure: "$SONAR_TOKEN"

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:$TAG
  - docker push $DOCKER_IMAGE_NAME