sudo: required
language: java
jdk:
  - oraclejdk8
env:
  global:
    secure: gBG9Vbc43WHzjQlVtJWYYv6LWRcUP2TiNFZGRQ7KmpR/Q7JMVuUi7lmu1SlpkYvNIMzyd/14BWlSuaV7NtEK7loECD23RbnLzeNv1gs08S+MkI5hzW3IBzp2VlCN9CuOFKxrmA3Fb+uvKpHjSG8JftUPOo3jq9F9IZ22lNEQ5vHXvTEA+m3e0mMgvB3gcqLwJdfYU+hSXcbRldQ2hPRyc8k2O6R859B8mpryDB0FPlYU/RQ1Yyyg3HqjSNdPbS08oxFR/8tYpdUoV19nb0oM7bogH9ODBejgt72CVBfxYnmsCNwK3QbQbUOnW2xfpYfIQNGFalxsZaw2GGCq/jY7rxI+1kvQyEidYz939CW9xIP0l8TeDfothf9Q+H2l7tSnu4e5yMMK/8Qj/iRSVuQji7/aAP4dIReskTG63gRE7WUaXgyXPUrfpAvojg0Rz4NeT2H5KtV2SYkYGeMDwZeHQ0AqoVaPSqBgKywf78+Gf6og3eI4I7Xytw+gFScgQ27+lvEGZQf+LT/9iTmNMnnQgrobuRYjgoozHZgrTBfn32NCsUzmnlyfdNXy85eJpR4LpdX7jMrExDveUhos9UZre2TKxGzmqGABZMnizmmmraKRehRsmtcaXBWFC+GR8uIXdCsde7ZXX6TBEjdEVT6m8G4y53uZz4lEMneKqrZ0JmU= #SONAR_TOKEN

script:
  - ./gradlew check test integrationTest jacocoTestCoverageVerification jacocoTestReport
  - sonar-scanner -X

addons:
  sonarcloud:
    organization: ismaelcabanas-github
    token:
      secure: "$SONAR_TOKEN"
