docker:
  host: "${DOCKER_IP:localhost}"

spring:
  datasource:
    url: "jdbc:postgresql://${docker.host}:5432/postgres?currentSchema=storeroom"
    username: postgres
    password: inf123sboj
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true # https://github.com/pgjdbc/pgjdbc/issues/1102