docker:
  host: "${DOCKER_IP:localhost}"

spring:
  datasource:
    url: "jdbc:postgresql://${docker.host}:5432/postgres?currentSchema=storeroom"
    username: postgres
    password: inf123sboj

jooq:
  package-name: cabanas.garcia.ismael.storeroom.product.infrastructure.framework.repository.jooq
  database: org.jooq.util.postgres.PostgresDatabase
