/*
 * This file is generated by jOOQ.
*/
package cabanas.garcia.ismael.storeroom.product.infrastructure.framework.repository.jooq.autogen;


import cabanas.garcia.ismael.storeroom.product.infrastructure.framework.repository.jooq.autogen.tables.Products;
import cabanas.garcia.ismael.storeroom.product.infrastructure.framework.repository.jooq.autogen.tables.records.ProductsRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>storeroom</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3",
        "schema version:storeroom_2018.08.02.1"
    },
    date = "2018-10-03T21:54:39.893Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ProductsRecord> PK_PRODUCTS = UniqueKeys0.PK_PRODUCTS;
    public static final UniqueKey<ProductsRecord> UQ_PRODUCTS_NAME = UniqueKeys0.UQ_PRODUCTS_NAME;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ProductsRecord> PK_PRODUCTS = createUniqueKey(Products.PRODUCTS, "pk_products", Products.PRODUCTS.P_ID);
        public static final UniqueKey<ProductsRecord> UQ_PRODUCTS_NAME = createUniqueKey(Products.PRODUCTS, "uq_products_name", Products.PRODUCTS.P_NAME);
    }
}
