/*
 * This file is generated by jOOQ.
*/
package cabanas.garcia.ismael.storeroom.product.infrastructure.framework.repository.jooq.autogen.tables.records;


import cabanas.garcia.ismael.storeroom.product.infrastructure.framework.repository.jooq.autogen.tables.Products;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Storeroom products
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3",
        "schema version:storeroom_2018.10.16.1"
    },
    date = "2018-10-16T19:46:42.297Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductsRecord extends UpdatableRecordImpl<ProductsRecord> implements Record4<UUID, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 527985216;

    /**
     * Setter for <code>storeroom.products.p_id</code>. Private product identifier
     */
    public void setPId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>storeroom.products.p_id</code>. Private product identifier
     */
    public UUID getPId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>storeroom.products.p_name</code>. Name of the product
     */
    public void setPName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>storeroom.products.p_name</code>. Name of the product
     */
    public String getPName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>storeroom.products.p_creation</code>. Time instant when it is created
     */
    public void setPCreation(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>storeroom.products.p_creation</code>. Time instant when it is created
     */
    public Timestamp getPCreation() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>storeroom.products.p_modification</code>. Instant of the last update
     */
    public void setPModification(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>storeroom.products.p_modification</code>. Instant of the last update
     */
    public Timestamp getPModification() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UUID, String, Timestamp, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UUID, String, Timestamp, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return Products.PRODUCTS.P_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Products.PRODUCTS.P_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Products.PRODUCTS.P_CREATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Products.PRODUCTS.P_MODIFICATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getPId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getPCreation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getPModification();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value1(UUID value) {
        setPId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value2(String value) {
        setPName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value3(Timestamp value) {
        setPCreation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord value4(Timestamp value) {
        setPModification(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductsRecord values(UUID value1, String value2, Timestamp value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductsRecord
     */
    public ProductsRecord() {
        super(Products.PRODUCTS);
    }

    /**
     * Create a detached, initialised ProductsRecord
     */
    public ProductsRecord(UUID pId, String pName, Timestamp pCreation, Timestamp pModification) {
        super(Products.PRODUCTS);

        set(0, pId);
        set(1, pName);
        set(2, pCreation);
        set(3, pModification);
    }
}
