CREATE TABLE PRODUCTS(
  P_ID           uuid NOT NULL,
  P_NAME         VARCHAR(50) NOT NULL,
  CONSTRAINT PK_PRODUCTS
  PRIMARY KEY (P_ID),
  CONSTRAINT UQ_PRODUCTS_NAME
  UNIQUE (P_NAME)
);
COMMENT ON TABLE PRODUCTS
IS 'Storeroom products';
COMMENT ON COLUMN PRODUCTS.P_ID
IS 'Private product identifier';
COMMENT ON COLUMN PRODUCTS.P_NAME
IS 'Name of the product';