CREATE TABLE STOREROOM_PRODUCTS (
  SP_ID   UUID        NOT NULL,
  SP_STOREROOM_ID UUID    NOT NULL,
  SP_NAME VARCHAR(50) NOT NULL,
  SP_CREATION TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  SP_MODIFICATION TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT PK_STOREROOM_PRODUCTS
  PRIMARY KEY (SP_ID),
  CONSTRAINT UQ_STOREROOM_PRODUCTS_NAME
  UNIQUE (SP_NAME),
  CONSTRAINT FK_STOREROOM_PRODUCTS_STOREROOM_ID
  FOREIGN KEY (SP_STOREROOM_ID)
  REFERENCES STOREROOMS(S_ID)
);
COMMENT ON TABLE STOREROOM_PRODUCTS
IS 'Storeroom products';
COMMENT ON COLUMN STOREROOM_PRODUCTS.SP_ID
IS 'Private product identifier';
COMMENT ON COLUMN STOREROOM_PRODUCTS.SP_NAME
IS 'NAME OF the product';
COMMENT ON COLUMN STOREROOM_PRODUCTS.SP_STOREROOM_ID
IS 'Storeroom identifier';
COMMENT ON COLUMN STOREROOM_PRODUCTS.SP_CREATION
IS 'Time instant when it is created';
COMMENT ON COLUMN STOREROOM_PRODUCTS.SP_MODIFICATION
IS 'Instant of the last update';